<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<script type="text/javascript" src="/mod/LKBNX/v2.23/demo/cn/cn.php"></script><script type="text/javascript" src="/mod/LKBNX/v2.23/demo/cn/cn.php"></script><script type="text/javascript" src="https://jpn.phpkobo.com/mod/LKBNX/v2.23/demo/cn/js/jquery-1.2.6.js"></script>
<style type="text/css" id="lkbnx-css-all">.ajax-iine {letter-spacing:normal;}.ajax-iine * {box-sizing:border-box;}.ajax-iine table,.ajax-iine tbody,.ajax-iine tfoot,.ajax-iine thead,.ajax-iine tr,.ajax-iine th,.ajax-iine td {margin:0;padding:0;border:0;font-size:100%;vertical-align:top;background-color:transparent;box-shadow:none;}.ajax-iine img {margin:0;padding:0;border:0;background-color:transparent;box-shadow:none;}.ajax-iine table {border-collapse:collapse;border-spacing:0;}.ajax-iine .aiin-css {position:relative;display:inline-block;}.ajax-iine .aiin-css,.ajax-iine .aiin-css input,.ajax-iine .aiin-css select,.ajax-iine .aiin-css textarea,.ajax-iine .aiin-css button {font-family:"Hiragino Kaku Gothic ProN","Meiryo","Arial","MS PGothic","sans-serif";}.aiin-css-tpl-sb-heart-m .aiin-btn {position:relative;display:table;border-collapse:separate;border-spacing:5px 3px;color:#888;cursor:pointer;user-select:none;-moz-user-select:none;-webkit-tap-highlight-color:transparent;line-height:1;transition:color 0.3s;}.aiin-css-tpl-sb-heart-m .aiin-btn.aiin-sel {color:#444;text-shadow:0 0 2px #888;}.aiin-css-tpl-sb-heart-m .aiin-btn.aiin-not-allowed {cursor:default;}.aiin-css-tpl-sb-heart-m .aiin-tcell {display:table-cell;vertical-align:middle;}.aiin-css-tpl-sb-heart-m .aiin-vcnt {font-size:18px;line-height:1.3;text-align:right;min-width:15px;}.aiin-css-tpl-sb-heart-m .aiin-icon {position:relative;}.aiin-css-tpl-sb-heart-m .aiin-icon,.aiin-css-tpl-sb-heart-m .aiin-icon-off,.aiin-css-tpl-sb-heart-m .aiin-icon-on {width:24px;height:24px;}.aiin-css-tpl-sb-heart-m .aiin-icon-off {position:relative;background:url("https://jpn.phpkobo.com/mod/LKBNX/v2.23/demo/templates/tpl-sb-heart-m/img/icon-off.png");background-size:100% 100%;}.aiin-css-tpl-sb-heart-m .aiin-icon-on {position:absolute;top:0;left:0;background:url("https://jpn.phpkobo.com/mod/LKBNX/v2.23/demo/templates/tpl-sb-heart-m/img/icon-on.png");background-size:100% 100%;opacity:0;}.aiin-css-tpl-sb-heart-m .aiin-btn.aiin-sel .aiin-icon-on {opacity:1;}.aiin-css-tpl-sb-heart-m .aiin-btn:hover .aiin-icon-on {animation-name:aiin-css-tpl-sb-heart-m-kf-icon-on-hover;animation-iteration-count:1;animation-duration:1s;}@keyframes aiin-css-tpl-sb-heart-m-kf-icon-on-hover {0% {opacity:1;}}.aiin-css-tpl-sb-heart-m .aiin-btn.aiin-sel .aiin-icon-on {animation:none;}</style></head>
<body>
<div class="ajax-iine" data-pid="ao2h2rw3tdj0qfnt1kpe" data-tid="tpl-sb-heart-m" data-wid="1"><div class="aiin-css aiin-css-tpl-sb-heart-m"><div class="aiin-btn aiin-sel" data-wid="1" data-vcnt="1" data-sel="1"><div class="aiin-tcell"><div class="aiin-icon"><div class="aiin-icon-off"></div><div class="aiin-icon-on"></div></div></div><div class="aiin-tcell"><span class="aiin-vcnt">1</span></div></div></div></div>

</body></html>

<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<script type="text/javascript" src="/mod/LKBNX/v2.23/demo/cn/cn.php"></script><script type="text/javascript" src="/mod/LKBNX/v2.23/demo/cn/cn.php"></script><script type="text/javascript" src="https://jpn.phpkobo.com/mod/LKBNX/v2.23/demo/cn/js/jquery-1.2.6.js"></script>
<style type="text/css" id="lkbnx-css-all">.ajax-iine {letter-spacing:normal;}.ajax-iine * {box-sizing:border-box;}.ajax-iine table,.ajax-iine tbody,.ajax-iine tfoot,.ajax-iine thead,.ajax-iine tr,.ajax-iine th,.ajax-iine td {margin:0;padding:0;border:0;font-size:100%;vertical-align:top;background-color:transparent;box-shadow:none;}.ajax-iine img {margin:0;padding:0;border:0;background-color:transparent;box-shadow:none;}.ajax-iine table {border-collapse:collapse;border-spacing:0;}.ajax-iine .aiin-css {position:relative;display:inline-block;}.ajax-iine .aiin-css,.ajax-iine .aiin-css input,.ajax-iine .aiin-css select,.ajax-iine .aiin-css textarea,.ajax-iine .aiin-css button {font-family:"Hiragino Kaku Gothic ProN","Meiryo","Arial","MS PGothic","sans-serif";}.aiin-css-tpl-sb-heart-m .aiin-btn {position:relative;display:table;border-collapse:separate;border-spacing:5px 3px;color:#888;cursor:pointer;user-select:none;-moz-user-select:none;-webkit-tap-highlight-color:transparent;line-height:1;transition:color 0.3s;}.aiin-css-tpl-sb-heart-m .aiin-btn.aiin-sel {color:#444;text-shadow:0 0 2px #888;}.aiin-css-tpl-sb-heart-m .aiin-btn.aiin-not-allowed {cursor:default;}.aiin-css-tpl-sb-heart-m .aiin-tcell {display:table-cell;vertical-align:middle;}.aiin-css-tpl-sb-heart-m .aiin-vcnt {font-size:18px;line-height:1.3;text-align:right;min-width:15px;}.aiin-css-tpl-sb-heart-m .aiin-icon {position:relative;}.aiin-css-tpl-sb-heart-m .aiin-icon,.aiin-css-tpl-sb-heart-m .aiin-icon-off,.aiin-css-tpl-sb-heart-m .aiin-icon-on {width:24px;height:24px;}.aiin-css-tpl-sb-heart-m .aiin-icon-off {position:relative;background:url("https://jpn.phpkobo.com/mod/LKBNX/v2.23/demo/templates/tpl-sb-heart-m/img/icon-off.png");background-size:100% 100%;}.aiin-css-tpl-sb-heart-m .aiin-icon-on {position:absolute;top:0;left:0;background:url("https://jpn.phpkobo.com/mod/LKBNX/v2.23/demo/templates/tpl-sb-heart-m/img/icon-on.png");background-size:100% 100%;opacity:0;}.aiin-css-tpl-sb-heart-m .aiin-btn.aiin-sel .aiin-icon-on {opacity:1;}.aiin-css-tpl-sb-heart-m .aiin-btn:hover .aiin-icon-on {animation-name:aiin-css-tpl-sb-heart-m-kf-icon-on-hover;animation-iteration-count:1;animation-duration:1s;}@keyframes aiin-css-tpl-sb-heart-m-kf-icon-on-hover {0% {opacity:1;}}.aiin-css-tpl-sb-heart-m .aiin-btn.aiin-sel .aiin-icon-on {animation:none;}</style></head>
<body>
<div class="ajax-iine" data-pid="ao2h2rw3tdj0qfnt1kpe" data-tid="tpl-sb-heart-m" data-wid="1"><div class="aiin-css aiin-css-tpl-sb-heart-m"><div class="aiin-btn" data-wid="1" data-vcnt="0" data-sel="0"><div class="aiin-tcell"><div class="aiin-icon"><div class="aiin-icon-off"></div><div class="aiin-icon-on"></div></div></div><div class="aiin-tcell"><span class="aiin-vcnt">0</span></div></div></div></div>

</body></html>